name: halal
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  path: any
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.13.0
  firebase_auth_platform_interface: ^7.0.4
  firebase_crashlytics: ^3.4.3
  http: ^0.13.3
  flutter_svg: ^2.0.8
  geolocator: ^9.0.2
  flutter_qiblah: ^2.2.0
  vector_graphics: ^1.1.7  
  sensors: ^2.0.3
  flutter_auth_ui: ^3.1.0
  barcode_scanner: ^3.6.2
  barcode_scan2: ^4.3.0
  simple_barcode_scanner: ^0.0.8
  cloud_firestore: ^4.13.6
  intl: ^0.19.0
  dropdown_search: ^5.0.6
  google_maps_webservice: ^0.0.20-nullsafety.5
  firebase_storage: ^11.6.9
  image_picker: ^0.8.4+3
  url_launcher: ^6.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logohalaltravel.jpg
    - assets/images/bgislamic.jpg
    - assets/images/bangkok.jpg
    - assets/images/compass.svg
    - assets/images/needle.svg
    - assets/images/compass.jpg
    - assets/images/3.svg
    - assets/images/4.svg
    - assets/images/5.svg
    - assets/images/mosque.jpg


